---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-cloud-controller-manager-operator
  name: cluster-cloud-controller-manager
  annotations:
    capability.openshift.io/name: CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:operator:cloud-controller-manager
  annotations:
    capability.openshift.io/name: CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators
  verbs:
  - get
  - create
  - list
  - watch

- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators/status
  resourceNames:
  - cloud-controller-manager
  verbs:
  - update

- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  - infrastructures
  - featuregates
  - networks
  - proxies
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - operator.openshift.io
  resources:
  - kubecontrollermanagers
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingadmissionpolicies
  - validatingadmissionpolicybindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

# vSphere has a separate node manager that uses the service account kube-system/vsphere-cloud-controller-manager.
# The operator must have these permissions to then grant them to the vSphere node manager.
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

# The operator must have these permissions to then grant them to the alibaba node manager. (note it also uses some of the ones requred by vsphere)
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - create
  - list
  - watch
  - update  
- apiGroups:
  - ""
  resources:
  - services
  - services/status
  verbs:
  - patch

# nutanix has a separate node manager that uses the service account kube-system/nutanix-cloud-controller-manager.
# The operator must have these permissions to then grant them to the nutanix node manager. (note it also uses some of the ones requred by vsphere)
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - patch

# gcp requires additional permissions on the kube-system/cloud-provider service account.
# The operator must have these permissions to then grant them to the gcp node manager.
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - update

# azure requires additional permissions on the openshift-cloud-controller-manager/cloud-controller-manager service account.
# The operator must have these permissions to then grant them to the azure cloud controller manager.
- apiGroups:
  - "discovery.k8s.io"
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-cloud-controller-manager
  namespace: openshift-cloud-controller-manager-operator
  annotations:
    capability.openshift.io/name: CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - create
      - update

  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - watch
      - list
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-cloud-controller-manager
  namespace: openshift-config
  annotations:
    capability.openshift.io/name: CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-cloud-controller-manager
  namespace: openshift-config
  annotations:
    capability.openshift.io/name: CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: cluster-cloud-controller-manager
    namespace: openshift-cloud-controller-manager-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-cloud-controller-manager
  namespace: openshift-config-managed
  annotations:
    capability.openshift.io/name: CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-cloud-controller-manager
  namespace: kube-system
  annotations:
    capability.openshift.io/name: CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
  # Azure needs these permissions, so to be able to install them, the operator needs them too.
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    resourceNames:
      - aks-managed-resource-locker
    verbs:
      - get
      - list
      - update
  # Create cannot be restricted by resource name
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-cloud-controller-manager
  namespace: openshift-config-managed
  annotations:
    capability.openshift.io/name: CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: cluster-cloud-controller-manager
    namespace: openshift-cloud-controller-manager-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:operator:cloud-controller-manager
  annotations:
    capability.openshift.io/name: CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
roleRef:
  kind: ClusterRole
  name: system:openshift:operator:cloud-controller-manager
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: openshift-cloud-controller-manager-operator
  name: cluster-cloud-controller-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-cloud-controller-manager
  namespace: openshift-cloud-controller-manager-operator
  annotations:
    capability.openshift.io/name: CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
roleRef:
  kind: Role
  name: cluster-cloud-controller-manager
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    namespace: openshift-cloud-controller-manager-operator
    name: cluster-cloud-controller-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-cloud-controller-manager
  namespace: openshift-cloud-controller-manager
  annotations:
    capability.openshift.io/name: CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    namespace: openshift-cloud-controller-manager-operator
    name: cluster-cloud-controller-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-cloud-controller-manager
  namespace: kube-system
  annotations:
    capability.openshift.io/name: CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
roleRef:
  kind: Role
  name: cluster-cloud-controller-manager
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    namespace: openshift-cloud-controller-manager-operator
    name: cluster-cloud-controller-manager
